# Generated by Django 5.1 on 2026-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="current_medications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="recent_medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="relevance_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
