# Generated by Django 5.1 on 2026-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_medicalprofile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalprofile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="emergency_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="profile_image_bucket",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="profile_image_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="profile_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="medicalprofile",
            name="relevant_clinical_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="allergies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="chronic_conditions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="current_medications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="recent_medical_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="medicalprofile",
            name="relevance_type",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
